
## Pour commencer {#SNSF-organisation}

### Logiciel et serveur

La cartographie des surfaces forestier et de la biomasse aérienne des arbres se fait avec le logiciel [R](https://www.r-project.org), dirigé à travers [RStudio](https://rstudio.com). Les scripts R sont mis à disposition dans un [dépot GitHub](https://github.com/ogardi/NERF-Togo). Les scripts dépendent des fois des outils GDAL disponible dans l'environnement, à installer pour les systèmes Linux avec `apt-get install python-gdal`.

Le traitement et l'analyse des images satellitaires demande des ressources intensives en terme de stockage de données (plusieurs TB) et capacité de calcul (plusieurs processeurs en parallèle). Les analyses pour le Niveau des emissions de référence pour les forêts du Togo (NERF 1.0) ont été éfféctués sur l'infrastructure informatique centrale de la BFH-HAFL (http://r.gro1.bfh.science, accès limité). Une fois la nouvelle infrastructure informatique puissante avec un serveur central au Ministère pour l'Environnement et Forêts (MERF) est  installé et disponible, les travaux peuvent être éffectués là. 

### Structure du répértoire

Les outils R dépendent d'une certaine structure des fichiers. Le répértoire de base `SNSF_Togo` est structuré comme suivant: 

```
SNSF_Togo
=========
├── data                                # Données de base externes ####################
    ├── GADM                              # <- frontières administratives
    ├── Landsat                           # <- images satellitaires
    ├── SRTM                              # <- données topographiques
    └── Worldclim                         # <- données climatiques
    
└── SNSF_v1.0_20200106                  # Répértoire SNSF v1.0 ########################
    ├── .Rprofile                         # [R] initialisation
    
    ├── 01_SSTS                           # SYSTÈME DE SURVEILLANCE TERRESTRE =========
        ├── 01_data                         #:: images et autres données pré-traités --
        └── 02_BdD                          #:: base de données SSTS ------------------
        
    ├── 02_IFN                            # INVENTAIRE FORESTIER NATIONAL =============
        └── 01_IFN-1                        #:: données d'inventaire IFN-1 ------------
    
    ├── 03_NRF-MRV                        # NIVEAU DE REFERENCE / MRV  ================
        ├── 01_MCF                          #:: Modification Couvert Forestier --------
        ├── 02_AGB                          #:: cartographie biomasse -----------------
        └── 03_report                       #:: rapport NRF/MRV -----------------------
        
    ├── 04_SNSF-manual                    #:: cette documentation du SNSF =============
    └── docs                              #:: cette documentation en HTML
    
    
└── SNSF_v1.x                           # Répértoire SNSF version actualisé ###########
```
<!-- old structure
```
SNSF_Togo
=========
├── data                                # Données de base externes ####################
    ├── GADM                              # <- frontières administratives
    ├── Landsat                           # <- images satellitaires
    ├── SRTM                              # <- données topographiques
    └── Worldclim                         # <- données climatiques
    
└── SNSF_v1.0_20200106                  # Répértoire SNSF v1.0 ########################
    ├── .Rprofile                         # [R] initialisation
    
    ├── 01_SSTS                           # SYSTÈME DE SURVEILLANCE TERRESTRE =========
        ├── 01_data                         #:: images et autres données pré-traités --
            └── ...
            
        ├── 02_BdD                          #:: base de données SSTS ------------------
             ├── 01_reseau-SSTS               #:: réseau de parcelles SSTS
                 ├── _create-grid.R             # [R] création réseau SSTS    
                 └── ...
             ├── 02_train-plots               #:: parcelles d'entraînement 
                 ├── _create-train-plots.R      # [R] création parcelles d'entraînement                                
                 └── ...             
             └── 03_val-plots                 #:: parcelles de validation
                 ├── _create-val-plots.R        # [R] création parcelles de validation
                 └── ... 
        
    ├── 02_IFN                            # INVENTAIRE FORESTIER NATIONAL =============
        ├── 01_field-data                   # <- données d'inventaire -----------------
        └── ... 
    
    ├── 03_NRF-MRV                        # NIVEAU DE REFERENCE / MRV  ================
        └── 01_MCF                          #:: Modification Couvert Forestier --------
            ├── _01_get-train-points.R        # [R] création des point d'entraînement
            ├── _02_create-FC-maps.R          # [R] calibration des cartes
            ├── _03_clean-FC-maps.R           # [R] nettoyage des cartes
            ├── _04_get-val-points.R          # [R] création des points de validation
            ├── _05_validate-FC-maps.R        # [R] validation des cartes
            ├── _06_FC-maps-accuracy.R        # [R] analyse de la précision des cartes
            ├── _07_analyse-FC-maps.R         # [R] analyse des cartes 
            └── output                        #:: résultats / cartes
                ├── 01_ref-maps                 # => cartes référence
                ├── 02_raw-maps                 # => cartes brutes
                ├── 03_clean-maps               # => cartes nettoyées
                ├── 04_validation               # => résultats validation
                └── 05_results                  # => résultats surfaces
        
        ├── 02_AGB                          #:: cartographie biomasse -----------------
            ├── _1_compile-AGB.R              # [R] évaluer inventaire
            ├── _2_create-AGB-maps.R          # [R] calibration des cartes
            ├── _3_clean-AGB-maps.R           # [R] nettoyage des cartes
            ├── _4_analyze-AGB.R              # [R] analyse des cartes
            └── output                        #:: cartes biomasse
                ├── 01_ref-maps                 # => cartes de référence
                └── 02_results                  # => résultats biomasse
        
        └── report                          #:: rapport NRF/MRV -----------------------
        
    ├── 04_manual                         #:: cette documentation du SNSF =============
    └── docs                              #:: cette documentation en HTML
    
    
└── SNSF_v1.x                           # Répértoire SNSF version actualisé ###########
```
-->

La structure du répertoire est définit dans le script R [.Rprofile](#NRF-set-up.R) et peut être ajousté.

C'est seulement les répétoires `src` et `manual` qui sont mis à diposition dans le dépôt [GitHub](https://github.com/ogardi/NERF-Togo). Les autres répétoires et données doivent être installés manuellement.

### Création d'un nouveau projet

Pour la création d'un nouveau projet avec le code le plus actuel, on clone le dépôt du projet sur GitHub par la commande `git clone --single-branch https://github.com/ogardi/NERF-Togo.git NOM-REPERTOIRE`. L'installation d'une version spécifique peut être fait avec `git clone -b VERSION --single-branch https://github.com/ogardi/NERF-Togo.git NOM-REPERTOIRE`. 

En travaillant avec RStudio, le plus facile est de créer directement un projet RStudio au départ due dépôt GitHub (`File > New Project ... > Version Control > Git`) avec les mêmes paramètre que l'installtion directe en haut.

Dans une prochaine étape, les données doivent être rendues disponibles, soit par une nouvelle acquisition, soit par une copie des répertoires existants.

* S'il n'est pas encore disponible, le répertoire `../data/` doit être créé et les données de base correspondantes doivent être fournies. 
* Dans le répertoire `./01_SSTS/02_BdD/`, le réseau d'échantillonnage ainsi que les données d'entraînement et de validation doivent être stockées.
* En outre, les données d'inventaire doivent être stockées dans le répertoire `./03_IFN/`.


### Définition des variables {#NRF-set-up.R}

Le traitement des images ainsi que les différentes analyses se font via des R-Scripts. Les variables et les fonctions utilisées dans les différents scripts sont définit dans le fichier `.Rprofile`, qui est automatiquement chargé au démarrage de R. Si le processus de chargement a réussi, vous pouvez voir un message de bienvenue suivant sur la console R.

Si aucun message n'apparaît, assurez-vous que a) R est lancé dans le répertoire et b) qu'aucun message d'erreur ne se produit. Les messages d'erreur possibles sont des paquets manquants (les paquets correspondants doivent être installés en premier) ou le fait de ne pas trouver les limites administratives de GADM dans `../data/GADM` (doivent également être installés en premier).

Si nécessaire les variables sont ajustées et R est redémarré. Notamment les informations sur la période analysée `YEARS.ALL` et les années à prendre en compte pour les différentes évaluations `YEARS.JNT`, `YEARS.VAL` et `YEARS.REF`.

#### Script R: `.Rprofile` {-}

```{r, code=readLines("../.Rprofile"), eval=FALSE}
```
