
## Organisation du travail {#SNSF-organisation}

### Logiciel et serveur

La cartographie des surfaces forestier et de la biomasse aérienne des arbres se fait avec le logiciel [R](https://www.r-project.org), dirigé à travers [RStudio](https://rstudio.com). Les scripts R sont mis à disposition dans un [dépot GitHub](https://github.com/ogardi/NERF-Togo). Les scripts dépendent des fois des outils GDAL disponible dans l'environnement, à installer pour les systèmes Linux avec `apt-get install python-gdal`.

Le traitement et l'analyse des images satellitaires demande des ressources intensives en terme de stockage de données (plusieurs TB) et capacité de calcul (plusieurs processeurs en parallèle). Les analyses pour le Niveau des emissions de référence pour les forêts du Togo (NERF 1.0) ont été éfféctués sur l'infrastructure informatique centrale de la BFH-HAFL (http://r.gro1.bfh.science, accès limité). Une fois la nouvelle infrastructure informatique puissante avec un serveur central au Ministère pour l'Environnement et Forêts (MERF) est  installé et disponible, les travaux peuvent être éffectués là. 

### Structure du répértoire

Les outils R dépendent d'une certaine structure des fichiers. Le répértoire de base `SNSF_Togo` est structuré comme suivant: 

```
SNSF_Togo
=========
├── data                                # Données de base #############################
    ├── GADM                              # <- frontières administratives
    ├── Landsat                           # <- images satellitaires
    ├── SRTM                              # <- données topographiques
    └── Worldclim                         # <- données climatiques
    
└── SNSF_v1.0_20200106                  # Répértoire SNSF v1.0 ########################
    ├── _set-up.R                         # [R] initialisation
    
    ├── 01_SSTS                           # SYSTÈME DE SURVEILLANCE TERRESTRE =========
        ├── 01_data                         #:: images et autres données pré-traités --
            ├── _prep-data.R                  # [R] prétraitement
            └── ...
            
        ├── 02_BdD                          #:: base de données SSTS ------------------
             ├── 01_reseau-SSTS               #:: réseau de parcelles SSTS
                 ├── _create-grid.R             # [R] création réseau SSTS    
                 └── ...
             ├── 02_train-plots               #:: parcelles d'entraînement 
                 ├── _create-train-plots.R      # [R] création parcelles d'entraînement                                
                 └── ...             
             └── 03_val-plots                 #:: parcelles de validation
                 ├── _create-val-plots.R        # [R] création parcelles de validation
                 └── ... 
        
    ├── 02_IFN                            # INVENTAIRE FORESTIER NATIONAL =============
        ├── 01_field-data                   # <- données d'inventaire -----------------
        └── ... 
    
    ├── 03_NRF-MRV                        # NIVEAU DE REFERENCE / MRV  ================
        └── 01_MCF                          #:: Modification Couvert Forestier --------
            ├── _01_get-train-points.R        # [R] création des point d'entraînement
            ├── _02_create-FC-maps.R          # [R] calibration des cartes
            ├── _03_clean-FC-maps.R           # [R] nettoyage des cartes
            ├── _04_get-val-points.R          # [R] création des points de validation
            ├── _05_validate-FC-maps.R        # [R] validation des cartes
            ├── _06_FC-maps-accuracy.R        # [R] analyse de la précision des cartes
            ├── _07_analyse-FC-maps.R         # [R] analyse des cartes 
            └── output                        #:: résultats / cartes
                ├── 01_ref-maps                 # => cartes référence
                ├── 02_raw-maps                 # => cartes brutes
                ├── 03_clean-maps               # => cartes nettoyées
                ├── 04_validation               # => résultats validation
                └── 05_results                  # => résultats surfaces
        
        ├── 02_AGB                          #:: cartographie biomasse -----------------
            ├── _1_compile-AGB.R              # [R] évaluer inventaire
            ├── _2_create-AGB-maps.R          # [R] calibration des cartes
            ├── _3_clean-AGB-maps.R           # [R] nettoyage des cartes
            ├── _4_analyze-AGB.R              # [R] analyse des cartes
            └── output                        #:: cartes biomasse
                ├── 01_ref-maps                 # => cartes de référence
                └── 02_results                  # => résultats biomasse
        
        └── report                          #:: rapport NRF/MRV -----------------------
        
    ├── 04_manual                         #:: cette documentation du SNSF =============
    └── docs                              #:: cette documentation en HTML
    
    
└── SNSF_v1.x                           # Répértoire SNSF version actualisé ###########
```

<!-- old structure
```
NRF_Togo

├── data                                    # Données de base ########################
    ├── GADM                                  # frontières administratives
    ├── IFN                                   # inventaire forestier national
    ├── Landsat                               # images satellitaires
    ├── SRTM                                  # données topographiques
    └── Worldclim                             # données climatiques
    
└── NRF_v1.0                                # Répétoire projet NRF v1.0 #############
    ├── input                                 # données spécifiques du projet
        ├── 1_images                            # images pre-traités                              
        ├── 2_train-plots                       # données d'entraînement                       
        └── 3_val-plots                         # données de validation
    ├── src                                   # scripts R ----------------------------
        ├── 0_set-up.R                          # initialisation
        ├── 1_prepare-images.R                  # préparation des images  
        ├── AGB                                 # cartographie biomasse
            ├── 2_compile-IFN.R                   # évaluer inventaire
            ├── 3_create-AGB-maps.R               # calibration des cartes
            ├── 4_clean-AGB-maps.R                # nettoyage des cartes
            └── 5_analyze-AGB.R                   # analyse des cartes
        └── FCC                                 # cartographie surfaces forestiers
            ├── 2_create-train-points.R           # création des point d'entraînement
            ├── 3_create-fc-maps.R                # calibration des cartes
            ├── 4_clean-fc-maps.R                 # nettoyage des cartes
            ├── 5_create-val-points.R             # création des points de validation
            ├── 6_validate-fc-maps.R              # validation des cartes
            ├── 7_fc-maps-accuracy.R              # analyse de la précision des cartes
            └── 8_analyse-fc-maps.R               # analyse des cartes  
    ├── output                                # résultats / cartes -------------------
        ├── 1_forest-cover                      # cartes surfaces forestiers
            ├── 1_ref-maps                        # cartes référence
            ├── 2_raw-maps                        # cartes brutes
            ├── 3_clean-maps                      # cartes nettoyées
            ├── 4_validation                      # résultats validation
            └── 5_results                         # résultats surfaces
        └── 2_biomass                           # cartes biomasse
            ├── 1_ref-maps                        # cartes de référence
            └── 5_results                         # résultats biomasse
    ├── report                                # rapport des résultats ----------------
    └── manuel                                # cette documentation ------------------
    
└── NRF_v1.x                                # Un autre répétoire projet #########
```
-->

La structure du répertoire est définit dans le script [0_set-up.R](#NRF-set-up.R) et peut être ajousté.

C'est seulement les répétoires `src` et `manual` qui sont mis à diposition dans le dépôt [GitHub](https://github.com/ogardi/NERF-Togo). Les autres répétoires et données doivent être installés manuellement.

### Création d'un nouveau projet

Pour la création d'un nouveau projet, le plus simple est de copier un projet existant, normalement le projet sur lequel on aimeriait continuer le travail. On peut faire ça à travers RStudio, SFTP ou directement sur le server par exemple `cp -r 2019_NERF_v1 2020_MNV_v0`. Après on efface les résultat de l'ancien projet `rm -r 2020_MNV_v0/output/*`. Les rapports on peut laisser, mais il faut les rédiger à la fin.

### Définition des variables {#NRF-set-up.R}

#### Description {-}

Le traitement des images ce fait par executer les scripts R, un après l'autre. Tout d'abord on ouvre et execute le script `0_set-up.R` pour charger les librairies et définir des variables qu'on utilise également dans les autres scripts. On peut également éxécuter l'ensemble du script par la commande R `source(0_set-up.R)`.

Les noms des variables définies dans le script `0_set-up.R` sont écrits en majuscules. Ils sont stockés dans l'environnement R et sont disponibles pour tous les autres scripts après l'exécution du script.

Avant l'exécution du script, les variables sont ajustées si nécessaire, notamment les informations sur la période analysée `PERIOD` et les années à prendre en compte pour les différentes évaluations `JNT.YEARS`, `VAL.YEARS` et `REF.YEARS`.

#### *0_set-up.R* {-}

```{r, code=readLines("../.Rprofile"), eval=FALSE}
```
