
# Analyses NRF/MRV {#NRF-MRV}

Le Togo a soumis son premier **Niveau de Référence pour les Forêts (NRF 1.0)** en Janvier 2020 ([*Soumissions du Togo sur la plateforme web REDD+ de la CCNUCC*](https://redd.unfccc.int/submissions.html?country=tgo)). Il est basé sur l'évolution de la couverture forestier entre 2003 -- 2018 (pertes et gains des terres forestières à une couverture du houppier ≥ 30%) et le stockage de carbone dans la biomasse aérienne des arbres (incl. bois mort sur pied)

Les données de base qu'on a utilisé pour effectuer ce travail sont: 

- **les images Landsat de l'archive USGS (1985 -- 2019)** et les **données climatiques WorldClim version 2** pour la la cartographie de l'évolution des surfaces forestiers et la cartographie de la biomasse
- **les données du SSTS (état 2019)** sur la couverture du houppier et l'utilisation des terres pour la calibration et la validation des cartes sur l'évolution des surfaces forestier
- **les données dendrométriques du IFN-1 (2015/16)** pour déterminer le stockage de carbone dans la biomasse aérienne par parcelle et la calibration des cartes de la biomasse

Ce chapitre décrit **l'approche méthodologique et les outils techniques** utilisés pour établir ce NRF. C'est un travail en cours. Le même approche sera utilisés a) pour améliorer le NRF avec des nouvelles données et/ou mèthodes et b) pour mettre à jour régulièrement les analyses dans le cadre du Monitoring, reporting et vérification (MRV). 

Chaque section commence par une description de la méthodologie utilisée et des références aux points clés dans le script R correspondant, suivie par une présentation exemplaire des résultats de cette étappe et enfin du code R commenté.

- **Section \@ref(SSTS-BdD)** décrit l'acquisition et la préparation des données de télédétection dans le cadre du Système de Surveillance Terrestre par Satellite SSTS (Images Landsat, données WorldClim, ...).
- **Section \@ref(SSTS-collecte)** décrit la collecte de données d'entraînement et de validation dans le cadre du SSTS.
- **Section \@ref(NRF-analyse-FCC)** décrit les différentes étapes nécessaires pour la cartographie des surfaces forestières et leur évolution: la classification des séries de cartes, leur néttoyage et validation.
- **Section \@ref(NRF-analyse-AGB)** décrit les différentes étapes nécessaires pour la cartographie des la biomasse aérienne: l'évaluation des données de l'IFN, la calibration des cartes de biomasse leur néttoyage et l'analyse de l'évolution de la biomasse dans le temps.